# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_auto_20180614_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(max_length=255)),
            ],
        ),
    ]
