# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-25 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_poi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'verbose_name_plural': 'Points of interest'},
        ),
    ]
